### PR TITLE
Travis CI setup for build check.

### PR DESCRIPTION
**Pull request by vivek-sethia**

### CODE REVIEW

**Comment by vivek-sethia** [comment]
@sacdallago I have included the Travis CI now

**Comment by vivek-sethia** [comment]
@sacdallago It's not passing since I am not passing the MongoDB credentials as environment variables. I am working on it.

**Comment by swathi-ssunder** [comment]
Finally 😌 
Can we merge this now ?

**Comment by sacdallago** [comment]
The problem on docker persists. The problem is in the Dockerfile (or package.json, for the reference).

You can open up the build and scroll to the bottom to find out the problem:

```
Step 8 : RUN grunt apidoc
 ---> Running in 49d6127281a5
>> Local Npm module "grunt-apidoc" not found. Is it installed?
Warning: Task "apidoc" not found. Use --force to continue.
```

https://hub.docker.com/r/pokemongoers/pokedata/builds/b76pdq27zhxwazk3qwhuw6t/

Please fix :) And you can fix it by trying to build on your own machine via the dockerfile ;)

**Comment by sacdallago** [comment]
Yet another hint: https://github.com/apidoc/grunt-apidoc

And another hint: `npm install grunt-apidoc --save-dev`

I feel like Oprah just giving out hints to everyone

**Comment by vivek-sethia** [comment]
@sacdallago  Yesterday, I did installed apidoc which was also reflected in `package.json` but I didn't do grunt-apidoc. I will do that now and build docker locally and see whether it works. Though docker was working locally even without this.

**Comment by sacdallago** [comment]
@vivek-sethia did you delete all of the previous containers+imgaes and were you actually using the version which had the dockerfile with that one RUN line?
Trust me on this one: with the current dockerfile and the current package.json, this machine would have never built :) Not locally, not remotely. If it did build locally, it shoulnd't have :P

**Comment by vivek-sethia** [comment]
@sacdallago I have the same docker file locally and it did build and I always run all the commands for stopping containers, deleting containers, and removing images. I am myself amazed by this and that's why I am now trying to include Docker build check along with Travis. :P

**Comment by sacdallago** [comment]
:D Mysteries!

I also was looking for someway to make docker build on PRs and not on merges, but had no luck so far. If you find something PLEASE let me know! :D I'd love to be able to build on PRs and even better, to deploy on PRs! Just imagine... the power.....

**Comment by sacdallago** [comment]
@vivek-sethia P.S.: This might be a workaround https://docs.travis-ci.com/user/docker/

**Comment by vivek-sethia** [comment]
@sacdallago I was reading the same and writing our code for Travis. :P

**Comment by sacdallago** [comment]
The only thing missing there is access the running docker instance from travis... But let's check it out first, maybe travis keeps the machine running and you can access it somehow, no idea

**Comment by swathi-ssunder** [comment]
With reference to https://github.com/PokemonGoers/PokeData/pull/93#issuecomment-243753167 , even I built locally(on OSX) using the Dockerfile and there was no failure. There are no errors, as they are on the remote. Wierd it is 😕

**Pull request merged**
