### PR TITLE
Fastpokemap extraction

### PR DESCRIPTION
**Pull request by jonas-he**
run with "npm run listen --collection=fastpokemap"

### CODE REVIEW

**Comment by swathi-ssunder** [comment]
@jonas-he, I pulled and executed the code.  

The initial logs showed 

```
INFO searcher active! latitude: 20 to 20.5, longitude: -159.5 to -159 
INFO Using proxy number 0: 0.0.0.0 
INFO Finished!
```

Data did not get inserted in the db..probably because of no data at these coordinates..
I let it continue.. 

Then there was this error

```
INFO searcher active! latitude: 30 to 35, longitude: -120 to -115 
INFO Using proxy number 0: 0.0.0.0 
INFO 
 length 2
INFO 2 Pokemon in this box! 
INFO 
 length 1
INFO 1 Pokemon in this box! 
ERROR SyntaxError: Unexpected token } in JSON at position 1223
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/swathissunder/workspace/rostlab/PokeData/app/services/mapService.js:141:41)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) 
INFO Finished!
```

After continuing further, there were a series of errors..

```
ERROR SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/swathissunder/workspace/rostlab/PokeData/app/services/mapService.js:137:45)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) 
```

And finally 

```
ERROR Timeout/Connection Reset occured! 
INFO Trying again!
```

**Comment by jonas-he** [comment]
@swathi-ssunder Timeout/Connection Reset is normal behaviour, because server blocks your IP after some amount of request, then after some time you get unblocked and it starts working again...

I forgot to remove a logger.error call for debugging purposes so these errors are not important because if they dont return valid JSON theres nothing i can do about it but ignore the response.

However i am wondering how you got the message "latitude: 30 to 35, longitude: -120 to -115 " because for fastpokemap i use a scan size of 0.5 x 0.5 ... did you really run with --collection=fastpokemap?

**Comment by swathi-ssunder** [comment]
@jonas-he - Yes, I understand the logic behind the timeout error. 
And I just executed `npm run listen --collection=fastpokemap`.
And inspite of these errors and letting it run for about 10-15 minutes, I still had no data inserted to the db.

**Comment by jonas-he** [comment]
@swathi-ssunder i ran it about 1 hour now and got around 5000 new pokemon, so yes it is a bit slow but i cant do anything against it since server is limiting requests. Will optimize scan areas in the future to make it faster.

**Comment by gyachdav** [comment]
Guys I don't have access to your sightings db. Can you report the number of sightings you already collected? Preferably it'd be great to gave a breakdown of sighting per source.

**Comment by jonas-he** [comment]
@gyachdav On my local MongoDB instance there are about 435k sightings overall:
PokeRadar: 180k
Skiplagged: 20k
Pokecrew: 225k
fastpokemap: 12k
The data was generated when i tested my scripts, so the time is not very uniformly distributed.
On the shared instance over at mlab there are about 2.5k sightings.

**Pull request merged**
